### ISSUE TITLE
curl localhost:3100/graphql -> curl: (56) Recv failure: Connection reset by peer

### ISSUE THREAD

**Issue by jcfd3** [cardano-foundation/cardano-graphql#743]
### Summary

Fully synced Cardano-DB-Sync however I've been getting this error ever since I started using GraphQL. I've never been able to check the sync status of DB-Sync with [https://github.com/input-output-hk/cardano-graphql#check-cardano-db-sync-progress](https://github.com/input-output-hk/cardano-graphql#check-cardano-db-sync-progress) either. 

### Steps to reproduce the bug

Running this `docker-compose.yml` with `sudo docker-compose up -d`
```
version: "3.5"

services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-11.5-alpine}
    environment:
      - POSTGRES_LOGGING=true
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
    shm_size: '2gb'
    volumes:
      # - postgres-data:/var/lib/postgresql/data
      - /home/ubuntu/adadata/postgres2:/var/lib/postgresql/data
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

# Removing this service and separating them (so I know exactly where the data is going and the mounted volumes)
  # cardano-node-ogmios:
  #   build:
  #     args:
  #       - NETWORK=${NETWORK:-mainnet}
  #     cache_from: [ cardanosolutions/cardano-node-ogmios:latest ]
  #     context: ./ogmios
  #   image: cardanosolutions/cardano-node-ogmios:${CARDANO_NODE_OGMIOS_VERSION:-v5.1.0}-${NETWORK:-mainnet}
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "400k"
  #       max-file: "20"
  #   ports:
  #     - ${OGMIOS_PORT:-1337}:1337
  #   restart: on-failure
  #   volumes:
  #     # - node-db:/db
  #     # - node-ipc:/ipc
  #     - /home/ubuntu/adadata:/mount

# MUST adjust the config.json to expose Prom Metrics! (All of the containers use the same default 'mainnet', and this has 'cardano-node' as well.
  cardano-node:
    image: inputoutput/cardano-node:${CARDANO_NODE_VERSION:-1.35.0}
#     environment:
#       - NETWORK=${NETWORK:-mainnet}
    command: [
      "run",
      "--config", "/config/config.json",
      "--database-path", "/mount/db2",
      "--socket-path", "/mount/ipc/node.socket",
      "--topology", "/config/topology.json",
      "--port", "3001"
    ]
    volumes:
      - ./ogmios/server/config/network/${NETWORK:-mainnet}/cardano-node:/config
      - ./ogmios/server/config/network/${NETWORK:-mainnet}/genesis:/genesis
      # - node-db:/data
      # - node-ipc:/ipc
      - /home/ubuntu/adadata:/mount
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    ports:
      - "12798:12798"
# # Don't need 3001:3001 b/c p2p. Can have Scott close it.

# Not sure if this will work, socket is correct volumed in w/ run commands.
  ogmios:
    image: cardanosolutions/ogmios:latest-${NETWORK:-mainnet}
    # build:
      # context: ./ogmios  # Changed, will this work?
      # target: ogmios
      # cache_from: [cardanosolutions/ogmios:latest]
    restart: on-failure
    command: [
      "--host", "0.0.0.0",
      "--node-socket", "/ipc/node.socket",
      "--node-config", "/config/cardano-node/config.json"
    ]
    volumes:
      - ./ogmios/server/config/network/${NETWORK:-mainnet}:/config
      # - node-ipc:/ipc
      - /home/ubuntu/adadata/ipc:/ipc
    ports:
      - ${OGMIOS_PORT:-1337}:1337

# This should be all set. Changed the volume locations to my local ones. And the default version of db-sync to 12.0.2
  cardano-db-sync-extended:
    image: inputoutput/cardano-db-sync:${CARDANO_DB_SYNC_VERSION:-13.0.0}
    command: [
      "--config", "/config/cardano-db-sync/config.json",
      "--socket-path", "/node-ipc/node.socket"
    ]
    environment:
      - EXTENDED=true
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - RESTORE_SNAPSHOT=${RESTORE_SNAPSHOT:-}
      - RESTORE_RECREATE_DB=N
    depends_on:
      # - cardano-node-ogmios
      - cardano-node
      - ogmios
      - postgres
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      - ./config/network/${NETWORK:-mainnet}:/config
      # - db-sync-data:/var/lib/cdbsync
      # Changed this line to 'cexplorer' b/c the GitHub repo has it as the file name.
      - /home/ubuntu/adadata/dbsync:/var/lib/cexplorer
      # - node-ipc:/node-ipc
      - /home/ubuntu/adadata/ipc:/node-ipc
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

# Not sure what this is, but I'll leave it for now
  hasura:
#     build:
#       context: ./packages/api-cardano-db-hasura/hasura
    image: inputoutput/cardano-graphql-hasura:${CARDANO_GRAPHQL_VERSION:-6.2.0}
    ports:
      - ${HASURA_PORT:-8090}:8080
    depends_on:
      - "postgres"
    restart: on-failure
    environment:
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_CORS_DOMAIN=http://localhost:9695
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

# This should be fine. Might need to adjust config stuff if it doesn't work.
  cardano-graphql:
#     build:
#       args:
#         - NETWORK=${NETWORK:-mainnet}
#         - METADATA_SERVER_URI=${METADATA_SERVER_URI:-https://tokens.cardano.org}
#       cache_from: [ inputoutput/cardano-graphql:latest ]
#       context: .
#       target: server
    image: inputoutput/cardano-graphql:${CARDANO_GRAPHQL_VERSION:-latest}-${NETWORK:-mainnet}
    environment:
      - ALLOW_INTROSPECTION=true
      - CACHE_ENABLED=true
      - LOGGER_MIN_SEVERITY=${LOGGER_MIN_SEVERITY:-info}
    expose:
      - ${API_PORT:-3100}
    ports:
      - ${API_PORT:-3100}:3100
    restart: on-failure
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

secrets:
  postgres_db:
    file: ./old-secrets/postgres_db
  postgres_password:
    file: ./old-secrets/postgres_password
  postgres_user:
    file: ./old-secrets/postgres_user
# volumes:
#   db-sync-data:
#   node-db:
#   node-ipc:
#   postgres-data:
```

Once DB-Sync has finished/caught up:
```
curl \
  -X POST \
  -H "Content-Type: application/json" \
  -d '{"query": "{ cardanoDbMeta { initialized syncPercentage }}"}' \
  http://localhost:3100/graphql
```

### Actual Result

```
curl: (56) Recv failure: Connection reset by peer
```

### Expected Result

```
{ cardanoDbMeta { initialized syncPercentage }}
```

https://github.com/input-output-hk/cardano-graphql#check-cardano-db-sync-progress

### Environment
```
                     | |
  ____   ____   ____ | |
 / ___) / _  | / _  || |
( (___ ( ( | || | | || |
 \____) \_|| | \_|| ||_|
       (_____|    |_|
{ os:
   { arch: 'x64',
     cpus:
      { count: 8,
        model: 'Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz' },
     release: '5.15.0-1015-aws',
     totalMem: 66599522304,
     type: 'Linux' },
  version: '6.2.0' }
```
### Platform

- [X] Linux (Ubuntu)
- [ ] Linux (Other)
- [ ] macOS
- [ ] Windows

### Runtime

- [ ] Node.js
- [X] Docker

### Runtime version

Docker version 20.10.12, build 20.10.12-0ubuntu2~20.04.1
