### ISSUE TITLE
replay block need too long time

### ISSUE THREAD

**Issue by RedheatWei** [cardano-foundation/cardano-graphql#894]
### Ask a question

when i restart cardano-node, it will replay whole block, but replay need too long time, about 10 hours.
how to skip it ?

docker-compose
```
  cardano-node:
    image: ghcr.io/intersectmbo/cardano-node:${CARDANO_NODE_VERSION:-9.1.0}
    environment:
      - NETWORK=${NETWORK:-mainnet}
    volumes:
      - ./node-ipc:/ipc
      - ./node-db:/node/db
      - ./config/network/${NETWORK:-mainnet}:/config
    entrypoint: cardano-node run --database-path /node/db --socket-path /ipc/node.socket --topology /config/cardano-node/topology.json --config /config/cardano-node/config.json
    networks:
      - ada-net
```
logs
```
[4dab0472:cardano.node.ChainDB:Info:5] [2024-09-03 12:11:09.26 UTC] Replayed block: slot 66182337 out of 133745329. Progress: 49.48%
[4dab0472:cardano.node.ChainDB:Info:5] [2024-09-03 12:11:12.24 UTC] Replayed block: slot 66203988 out of 133745329. Progress: 49.50%
[4dab0472:cardano.node.ChainDB:Info:5] [2024-09-03 12:11:14.23 UTC] Replayed block: slot 66225541 out of 133745329. Progress: 49.52%
[4dab0472:cardano.node.ChainDB:Info:5] [2024-09-03 12:11:17.38 UTC] Replayed block: slot 66247184 out of 133745329. Progress: 49.53%
```
